### ISSUE TITLE
Extra close bracket and space when Tidy CSS is run

### ISSUE THREAD

**Issue by bjankord** [fitnr/SublimeCSSTidy#3]
Using the default settings, when I run Tidy CSS, the following code

``` css
div{
    font-size:1em;
    background:#f00;
}
```

is converted to 

``` css
div {
font-size:1em;
background:red;
}
}


```
